import Head from 'next/head'
import { ReactNode, useState } from 'react'
import Header from '../components/organisms/header'
import Footer from '../components/organisms/footer'
import useThemeDetector from '../hooks/useThemeDetector'

export interface LayoutProps {
	children: ReactNode
}

export default function Layout({ children }: LayoutProps) {
	const isDarkTheme = useThemeDetector()

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link
					rel='icon'
					href={isDarkTheme ? '/favicon-light.svg' : '/favicon-dark.svg'}
				/>
			</Head>
			<Header />
			<main>{children}</main>
			<Footer />
		</>
	)
}
